name: SoulCommands
main: de.elia.Main
bootstrapper: de.elia.systemclasses.BootsTrapper
loader: de.elia.systemclasses.Loader
api-version: '1.20'
version: '2.0.1'
authors:
  - Elia
  - Gemmerr
  - Wate
description: SoulSMP Tools
has-open-classloader: true

dependencies:
  server:
    BetterTeams:
      required: true
    LuckPerms:
      required: true
